source 'https://supermarket.getchef.com'
cookbook 'python', git: 'git://github.com/poise/python.git'
cookbook 'nginx-django', git: 'git://github.com/btnz/opsworks-chef.git', rel: 'nginx-django'
cookbook 'gunicorn', git: 'git://github.com/opscode-cookbooks.git'
